name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: ConfigurationSubstitutor/ConfigurationSubstitution.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
